### ISSUE TITLE
dns-zone record set create command fails for type SOA with missing field exception

### ISSUE THREAD

**Issue by anuchandy** [MSOpenTech/azure-sdk-tools-xplat#139]
_From @babumuralidharan on April 24, 2015 6:52_

* create dns-zone record set create for type SOA.
* command fails with missing fields host & email.

___verbose output below___

```
node bin/azure network dns-zone record-set create crp-dev-test-tm1 crpdevtestdnszone2 crpdevtestdnszone2rs2 --type SOA -vv
info:    Executing command network dns-zone record-set create
verbose: Looking up the dns zone "crpdevtestdnszone2"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { user-agent: 'WindowsAzureXplatCLI/0.9.0', Content-Type: 'application/json; charset=utf-8' },
silly:       url: 'https://api-current.resources.windows-int.net/subscriptions/e66a2b71-7bad-41c1-907a-108aa3565c0f/resourceGroups/crp-dev-test-tm1/providers/Microso
ft.Network/dnszones/crpdevtestdnszone2?api-version=2015-05-04-preview'
silly:   }
Using Token:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCIsImtpZCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCJ9.eyJhdWQiOiJodHRwczov
L21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLXBwZS5uZXQvZGUzNzEwMTAtZTgwYy00MjU3LThmZGMtNGJmYTRkNmVmZTA4LyIsImlhdCI6MTQyOTg1NzU2NCwib
mJmIjoxNDI5ODU3NTY0LCJleHAiOjE0Mjk4NjE0NjQsInZlciI6IjEuMCIsInRpZCI6ImRlMzcxMDEwLWU4MGMtNDI1Ny04ZmRjLTRiZmE0ZDZlZmUwOCIsIm9pZCI6IjEwODRmZjRmLWM2N2MtNGNkMC1hYTMzLWY0OT
g0OTNmYmYwNiIsImVtYWlsIjoiYXV4dG0xOTVAbGl2ZS5jb20iLCJwdWlkIjoiMTAwMzNGRkY4QUZFRjREMSIsImlkcCI6ImxpdmUuY29tIiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDNCRkZEQzNGODhBMzciLCJ
zdWIiOiJUQ2FWZUlEWXlqc1l4YmhYbHJsQTBuN3dnUlBnNHo0Z3ZKaG5aUlctS0M0IiwibmFtZSI6ImF1eHRtMTk1QGxpdmUuY29tIiwiYW1yIjpbInB3ZCJdLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2F1eHRtMTk1
QGxpdmUuY29tIiwiYXBwaWQiOiIxOTUwYTI1OC0yMjdiLTRlMzEtYTljZi03MTc0OTU5NDVmYzIiLCJhcHBpZGFjciI6IjAiLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJhY3IiOiIxIn0.ZVB4QfOKW2OP_yBe9
UCA9yyjLjY8fgsu4WJZU2FX_UjZRXxD9lS6j8hqWozHtF2SN3uB-pQUYa3y02oXrnTiI3mHVFX_bC6YYSpT7m1a3yyuXXqNRIdipGuroctheWAt1Fgv6jeLSQ__IigniW8XoEzgMpBEzlrnaqyUFYv97AfK4dIsn9Pnn7
Ux6fyuhLjFyVbJuduIhP7Nuf6nMMpkRSKKKrEJWxlJHZVGqD174CICVQkwLzPZX5hjTJqPfD85mdm_QzgZI6sWqZ5W3NS36UFNoMvQ4KX49G9_yg-5dECr9wOLAoSifYsDOZ--5Zn0V2LUTZDc1iIERjnS720eAw
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'private',
silly:           etag: '27554f58-4b27-4a15-95ec-b9380b1f896c',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           x-aspnet-version: '4.0.30319',
silly:           x-ms-request-id: '2866b6f8-579c-4cc9-a8e6-27ed71b4135c',
silly:           x-ms-ratelimit-remaining-subscription-resource-requests: '11994',
silly:           date: 'Fri, 24 Apr 2015 06:48:30 GMT',
silly:           content-type: 'application/json; charset=utf-8',
silly:           x-ms-routing-request-id: 'CENTRALUS:20150424T064831Z:e524b26e-43a3-4a36-b8df-be5ccd5fc64b',
silly:           x-content-type-options: 'nosniff',
silly:           server: 'Microsoft-IIS/7.5',
silly:           content-length: '348',
silly:           x-ms-correlation-request-id: 'e524b26e-43a3-4a36-b8df-be5ccd5fc64b',
silly:           x-powered-by: 'ASP.NET'
silly:       },
silly:       body: '{"id":"\\/subscriptions\\/e66a2b71-7bad-41c1-907a-108aa3565c0f\\/resourceGroups\\/crp-dev-test-tm1\\/providers\\/Microsoft.Network\\/dnszones\\/c
rpdevtestdnszone2","name":"crpdevtestdnszone2","type":"Microsoft.Network\\/dnszones","etag":"27554f58-4b27-4a15-95ec-b9380b1f896c","location":"global","tags":{"tag1"
:"dns1"},"properties":{"numberOfRecordSets":5}}'
silly:   }
info:    --ttl parameter is not specified, using default TTL - "4"
verbose: Looking up the DNS record set "crpdevtestdnszone2rs2"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { user-agent: 'WindowsAzureXplatCLI/0.9.0', Content-Type: 'application/json; charset=utf-8' },
silly:       url: 'https://api-current.resources.windows-int.net/subscriptions/e66a2b71-7bad-41c1-907a-108aa3565c0f/resourceGroups/crp-dev-test-tm1/providers/Microso
ft.Network/dnszones/crpdevtestdnszone2/SOA/crpdevtestdnszone2rs2?api-version=2015-05-04-preview'
silly:   }
Using Token:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCIsImtpZCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCJ9.eyJhdWQiOiJodHRwczov
L21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLXBwZS5uZXQvZGUzNzEwMTAtZTgwYy00MjU3LThmZGMtNGJmYTRkNmVmZTA4LyIsImlhdCI6MTQyOTg1NzU2NCwib
mJmIjoxNDI5ODU3NTY0LCJleHAiOjE0Mjk4NjE0NjQsInZlciI6IjEuMCIsInRpZCI6ImRlMzcxMDEwLWU4MGMtNDI1Ny04ZmRjLTRiZmE0ZDZlZmUwOCIsIm9pZCI6IjEwODRmZjRmLWM2N2MtNGNkMC1hYTMzLWY0OT
g0OTNmYmYwNiIsImVtYWlsIjoiYXV4dG0xOTVAbGl2ZS5jb20iLCJwdWlkIjoiMTAwMzNGRkY4QUZFRjREMSIsImlkcCI6ImxpdmUuY29tIiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDNCRkZEQzNGODhBMzciLCJ
zdWIiOiJUQ2FWZUlEWXlqc1l4YmhYbHJsQTBuN3dnUlBnNHo0Z3ZKaG5aUlctS0M0IiwibmFtZSI6ImF1eHRtMTk1QGxpdmUuY29tIiwiYW1yIjpbInB3ZCJdLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2F1eHRtMTk1
QGxpdmUuY29tIiwiYXBwaWQiOiIxOTUwYTI1OC0yMjdiLTRlMzEtYTljZi03MTc0OTU5NDVmYzIiLCJhcHBpZGFjciI6IjAiLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJhY3IiOiIxIn0.ZVB4QfOKW2OP_yBe9
UCA9yyjLjY8fgsu4WJZU2FX_UjZRXxD9lS6j8hqWozHtF2SN3uB-pQUYa3y02oXrnTiI3mHVFX_bC6YYSpT7m1a3yyuXXqNRIdipGuroctheWAt1Fgv6jeLSQ__IigniW8XoEzgMpBEzlrnaqyUFYv97AfK4dIsn9Pnn7
Ux6fyuhLjFyVbJuduIhP7Nuf6nMMpkRSKKKrEJWxlJHZVGqD174CICVQkwLzPZX5hjTJqPfD85mdm_QzgZI6sWqZ5W3NS36UFNoMvQ4KX49G9_yg-5dECr9wOLAoSifYsDOZ--5Zn0V2LUTZDc1iIERjnS720eAw
silly:   returnObject
silly:   {
silly:       statusCode: 404,
silly:       header: {
silly:           cache-control: 'private',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           x-aspnet-version: '4.0.30319',
silly:           x-ms-request-id: 'c6991076-f79c-4306-b05f-b1a1f9496503',
silly:           date: 'Fri, 24 Apr 2015 06:48:06 GMT',
silly:           content-type: 'application/json; charset=utf-8',
silly:           x-ms-routing-request-id: 'CENTRALUS:20150424T064806Z:5b5a9673-7add-461b-8652-a4facd731027',
silly:           x-content-type-options: 'nosniff',
silly:           server: 'Microsoft-IIS/7.5',
silly:           content-length: '183',
silly:           x-ms-ratelimit-remaining-subscription-reads: '31997',
silly:           x-ms-correlation-request-id: '5b5a9673-7add-461b-8652-a4facd731027',
silly:           x-powered-by: 'ASP.NET'
silly:       },
silly:       body: "{"code":"NotFound","message":"The resource record 'crpdevtestdnszone2rs2' does not exist in resource group 'crp-dev-test-tm1' of subscription 'e6
6a2b71-7bad-41c1-907a-108aa3565c0f'."}"
silly:   }
verbose: Creating DNS record set "crpdevtestdnszone2rs2"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'PUT',
silly:       headers: {
silly:           user-agent: 'WindowsAzureXplatCLI/0.9.0',
silly:           Content-Length: 44,
silly:           Content-Type: 'application/json; charset=utf-8'
silly:       },
silly:       url: 'https://api-current.resources.windows-int.net/subscriptions/e66a2b71-7bad-41c1-907a-108aa3565c0f/resourceGroups/crp-dev-test-tm1/providers/Microso
ft.Network/dnszones/crpdevtestdnszone2/SOA/crpdevtestdnszone2rs2?api-version=2015-05-04-preview',
silly:       body: '{"properties":{"TTL":4},"location":"global"}'
silly:   }
Using Token:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCIsImtpZCI6IjVUa0d0S1JrZ2FpZXpFWTJFc0xDMmdPTGpBNCJ9.eyJhdWQiOiJodHRwczov
L21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLXBwZS5uZXQvZGUzNzEwMTAtZTgwYy00MjU3LThmZGMtNGJmYTRkNmVmZTA4LyIsImlhdCI6MTQyOTg1NzU2NCwib
mJmIjoxNDI5ODU3NTY0LCJleHAiOjE0Mjk4NjE0NjQsInZlciI6IjEuMCIsInRpZCI6ImRlMzcxMDEwLWU4MGMtNDI1Ny04ZmRjLTRiZmE0ZDZlZmUwOCIsIm9pZCI6IjEwODRmZjRmLWM2N2MtNGNkMC1hYTMzLWY0OT
g0OTNmYmYwNiIsImVtYWlsIjoiYXV4dG0xOTVAbGl2ZS5jb20iLCJwdWlkIjoiMTAwMzNGRkY4QUZFRjREMSIsImlkcCI6ImxpdmUuY29tIiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDNCRkZEQzNGODhBMzciLCJ
zdWIiOiJUQ2FWZUlEWXlqc1l4YmhYbHJsQTBuN3dnUlBnNHo0Z3ZKaG5aUlctS0M0IiwibmFtZSI6ImF1eHRtMTk1QGxpdmUuY29tIiwiYW1yIjpbInB3ZCJdLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2F1eHRtMTk1
QGxpdmUuY29tIiwiYXBwaWQiOiIxOTUwYTI1OC0yMjdiLTRlMzEtYTljZi03MTc0OTU5NDVmYzIiLCJhcHBpZGFjciI6IjAiLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJhY3IiOiIxIn0.ZVB4QfOKW2OP_yBe9
UCA9yyjLjY8fgsu4WJZU2FX_UjZRXxD9lS6j8hqWozHtF2SN3uB-pQUYa3y02oXrnTiI3mHVFX_bC6YYSpT7m1a3yyuXXqNRIdipGuroctheWAt1Fgv6jeLSQ__IigniW8XoEzgMpBEzlrnaqyUFYv97AfK4dIsn9Pnn7
Ux6fyuhLjFyVbJuduIhP7Nuf6nMMpkRSKKKrEJWxlJHZVGqD174CICVQkwLzPZX5hjTJqPfD85mdm_QzgZI6sWqZ5W3NS36UFNoMvQ4KX49G9_yg-5dECr9wOLAoSifYsDOZ--5Zn0V2LUTZDc1iIERjnS720eAw
silly:   returnObject
silly:   {
silly:       statusCode: 400,
silly:       header: {
silly:           cache-control: 'private',
silly:           x-ms-ratelimit-remaining-subscription-writes: '1198',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           x-aspnet-version: '4.0.30319',
silly:           x-ms-request-id: 'a4628a1c-bb42-4515-9959-673406338508',
silly:           date: 'Fri, 24 Apr 2015 06:48:32 GMT',
silly:           content-type: 'application/json; charset=utf-8',
silly:           x-ms-routing-request-id: 'CENTRALUS:20150424T064833Z:4a50bfc6-8c19-4eae-852b-99a612755638',
silly:           x-content-type-options: 'nosniff',
silly:           server: 'Microsoft-IIS/7.5',
silly:           content-length: '124',
silly:           x-ms-correlation-request-id: '4a50bfc6-8c19-4eae-852b-99a612755638',
silly:           x-powered-by: 'ASP.NET'
silly:       },
silly:       body: "{"code":"BadRequest","message":"The resource record is missing field 'host'. The resource record is missing field 'email'."}"
silly:   }
error:   The resource record is missing field 'host'. The resource record is missing field 'email'.
silly:   {
silly:       stack: "Error: The resource record is missing field 'host'. The resource record is missing field 'email'.\n  <<< async stack >>>\n  at create__1 (C:\\In
teropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\dnsRecordSet._js:34:43)\n  at createDnsRecordSet__61 (C
:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\networkClient._js:424:18)\n  at __61 (C:\\InteropP
rojects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\network._js:1194:21)\n  <<< raw stack >>>\n    at Function.Se
rviceClient._normalizeError (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\services\\servic
eclient.js:815:23)\n    at C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\services\\filters\
\errorhandlingfilter.js:44:29\n    at Request._callback (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-c
ommon\\lib\\http\\request-pipeline.js:109:14)\n    at Request.self.callback (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\n
ode_modules\\azure-common\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (C:\\InteropProjects\\XPlat-C
li\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:14)\n    at Request.emit (events.js:117
:20)\n    at IncomingMessage.<anonymous> (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_mod
ules\\request\\request.js:1111:12)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:943:16\n",
silly:       arguments: undefined,
silly:       type: undefined,
silly:       message: "The resource record is missing field 'host'. The resource record is missing field 'email'.",
silly:       code: 'BadRequest',
silly:       statusCode: 400,
silly:       requestId: 'a4628a1c-bb42-4515-9959-673406338508',
silly:       __frame: {
silly:           name: 'create__1',
silly:           line: 17,
silly:           file: 'C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\dnsRecordSet._js',
silly:           prev: {
silly:               name: 'createDnsRecordSet__61',
silly:               line: 420,
silly:               file: 'C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\networkClient._js',
silly:               prev: {
silly:                   name: '__61',
silly:                   line: 1188,
silly:                   file: 'C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\lib\\commands\\arm\\network\\network._js',
silly:                   prev: undefined,
silly:                   calls: 4,
silly:                   active: false,
silly:                   offset: 6,
silly:                   col: 20
silly:               },
silly:               calls: 1,
silly:               active: false,
silly:               offset: 4,
silly:               col: 17
silly:           },
silly:           calls: 2,
silly:           active: false,
silly:           offset: 17,
silly:           col: 42
silly:       },
silly:       rawStack: "Error: The resource record is missing field 'host'. The resource record is missing field 'email'.\n    at Function.ServiceClient._normalizeEr
ror (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\services\\serviceclient.js:815:23)\n
at C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\services\\filters\\errorhandlingfilter.js:
44:29\n    at Request._callback (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\lib\\http\\reques
t-pipeline.js:109:14)\n    at Request.self.callback (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-commo
n\\node_modules\\request\\request.js:199:22)\n    at Request.emit (events.js:98:17)\n    at Request.<anonymous> (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\A
pril23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_modules\\request\\request.js:1160:14)\n    at Request.emit (events.js:117:20)\n    at IncomingMes
sage.<anonymous> (C:\\InteropProjects\\XPlat-Cli\\ARM\\opentechrepo\\April23_tmhack\\azure-xplat-cli-pr\\node_modules\\azure-common\\node_modules\\request\\request.j
s:1111:12)\n    at IncomingMessage.emit (events.js:117:20)\n    at _stream_readable.js:943:16\n"
silly:   }
info:    Error information has been recorded to C:\Users\v-bamura\.azure\azure.err
verbose: Error: The resource record is missing field 'host'. The resource record is missing field 'email'.
  <<< async stack >>>
  at create__1 (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\lib\commands\arm\network\dnsRecordSet._js:34:43)
  at createDnsRecordSet__61 (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\lib\commands\arm\network\networkClient._js:424:18)
  at __61 (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\lib\commands\arm\network\network._js:1194:21)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\node_modules\azure-common\lib\services
\serviceclient.js:815:23)
    at C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\node_modules\azure-common\lib\http\request-pipeline.js:109:
14)
    at Request.self.callback (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\node_modules\azure-common\node_modules\request\request.
js:199:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\node_modules\azure-common\node_modules\request\request.js
:1160:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\InteropProjects\XPlat-Cli\ARM\opentechrepo\April23_tmhack\azure-xplat-cli-pr\node_modules\azure-common\node_modules\request\re
quest.js:1111:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16

error:   network dns-zone record-set create command failed

```

_Copied from original issue: MSOpenTech/azure-xplat-cli-pr#476_

**Comment by anuchandy** [comment]
_From @roman-boltunov on April 24, 2015 11:42_

Hi @babumuralidharan. Thanks for sharing, will report this issue.

**Comment by anuchandy** [comment]
@roman-boltunov Just confirming.. 

The above log (output of -vv) shows PUT body as:

body: '{"properties":{"TTL":4},"location":"global"}'

It is missing SOA fields.

There are two possibilities here:


1. Either SDK is not serializing 'recordSet.properties.soaRecord' object
2. Or the object we are passing to SDK is missing this 'recordSet.properties.soaRecord'  property. 

Can we check this? if issue is 1 then we should report to DNS hyak team

**Comment by anuchandy** [comment]
_From @roman-boltunov on April 27, 2015 9:43_

Hi @anuchandy, for 'record-set create' command we do not provide any information about 'inner' records.
For example we provide record-related information by using 'record-set add-record' command, i.e. adding a record to **existing** record-set, and here we can set --host and --email fields. But 'record-set create' command just creates an empty record-set of specified type.
So the issue is that 'record-set create' command asks us to provide 'inner' record-related information while creating empty record-set.
Please let me know if you have any questions on this.

**Comment by anuchandy** [comment]
_From @roman-boltunov on April 27, 2015 10:2_

@anuchandy, just tried to provide fake --host and --email parameters while creating SOA record-set, then it asks for whole set of parameters (host, email, expireTime, minimumTtl, refreshTime, retryTime, serialNumber). I've provided them and got new error: 
**Error: Cannot create SOA records. A zone can only contain one SOA record at the zone root.**
But I've checked that DNS zone does not contain any SOA record-set:
```
data:    Name                 Location  TTL   Type                              Tags
data:    -------------------  --------  ----  --------------------------------  ------------
data:    @                    global    3600  Microsoft.Network/dnszones
data:    @                    global    3600  Microsoft.Network/dnszones
data:    test-ns-record       global    4     Microsoft.Network/dnszones
data:    test-record          global    4     Microsoft.Network/dnszones/A
data:    test-record1         global    4     Microsoft.Network/dnszones
data:    test-txt-record      global    54    Microsoft.Network/dnszones/TXT    tag3=txttag3
data:    testrecordtypea      global    12    Microsoft.Network/dnszones/A
data:    testrecordtypeaaaa   global    4     Microsoft.Network/dnszones/AAAA
data:    testrecordtypecname  global    13    Microsoft.Network/dnszones/CNAME
data:    testrecordtypemx     global    4     Microsoft.Network/dnszones/MX
data:    testrecordtypens     global    4     Microsoft.Network/dnszones
data:    testrecordtypesrv    global    4     Microsoft.Network/dnszones/SRV
data:    testrecordtypetxt    global    4     Microsoft.Network/dnszones/TXT
```

**Comment by anuchandy** [comment]
_From @roman-boltunov on April 27, 2015 10:5_

Here is the -vv for 'record-set create' using type SOA:
https://gist.github.com/roman-boltunov/1d248be5ec5692734d1d

**Comment by anuchandy** [comment]
This issue was moved to MSOpenTech/azure-xplat-cli-pr#518
